# Generated by Django 3.1.12 on 2021-06-28 13:41

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_braintree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
